name: .NET Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x' # atau versi .NET yang sesuai dengan proyek Anda

      - name: Install MSBuild
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get install -y software-properties-common
          wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y msbuild
          
      - name: Restore dependencies
        run: dotnet restore Android_UEFIInstaller.sln # Ganti <NAMA_FILE> dengan nama file .sln Anda

      - name: Build project
        run: msbuild Android_UEFIInstaller.sln /p:Configuration=Release
        
      - name: Run tests
        run: dotnet test Android_UEFIInstaller.sln --no-build --verbosity normal

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./output
